### ISSUE TITLE
App.jsx routing

### ISSUE THREAD

**Issue by sanehirakenji** [carpool-and-go/carpool-and-go#13]
Please do work for this task in a branch called issue-008.

Modify App.jsx to re-route the user to the newly created pages specifically for carpool-and-go.

Robin Updated 4/8:
<img width="1069" alt="App jsx" src="https://user-images.githubusercontent.com/97719124/163473765-8c584540-a873-4c20-9396-215275d5e0ae.png">

**Comment by robindum** [comment]
4/8 Finished:
<img width="1069" alt="image" src="https://user-images.githubusercontent.com/97719124/163473824-c0c7054b-95c2-4b54-b1ad-c1c53de13329.png">
