### ISSUE TITLE
Finish Fast Ride Feed/Form

### ISSUE THREAD

**Issue by sanehirakenji** [carpool-and-go/carpool-and-go#41]
Please do work for this task in a branch called issue-041.

Implement a fast ride form that pushes fast ride requests to the fast ride feed.

**Comment by kaialii** [comment]
<img width="1437" alt="Screen Shot 2022-04-24 at 8 29 48 PM" src="https://user-images.githubusercontent.com/31085175/165033381-d0cd8201-9a5e-40ee-8853-cf0f42b7a83c.png">
<img width="1438" alt="Screen Shot 2022-04-24 at 8 30 06 PM" src="https://user-images.githubusercontent.com/31085175/165033400-60d70a47-0923-45a8-a839-16a74b135d10.png">
<img width="1438" alt="Screen Shot 2022-04-24 at 8 30 15 PM" src="https://user-images.githubusercontent.com/31085175/165033408-728bc696-2205-424e-b038-937b9d8f1b22.png">

**Comment by kaialii** [comment]
draft of issue-041: Form populates data into Feed page. Feed page does not have a working "edit" nor does if have a working "submit" button for notes, as of yet... photos attached to project issue-041... merged to master...

**Comment by kaialii** [comment]
<img width="350" alt="Screen Shot 2022-04-28 at 10 38 02 AM" src="https://user-images.githubusercontent.com/31085175/165841613-f17520d9-8995-40f4-8d64-e6be42749ccc.png">
